rooms = [
    {"title": "Entry", "description": "You are in room: Entry" },
    {"title": "Living Room", "description": "You are in room: Living Room" },
    {"title": "Closet", "description": "You are in room: Closet" },
    {"title": "Secret Room", "description": "You are in room: Secret Room" },
    {"title": "Dining Room", "description": "You are in room: Dining Room" },
    {"title": "Hallway", "description": "You are in room: Hallway" },
    {"title": "Master Bedroom", "description": "You are in room: Master Bedroom" },
    {"title": "Master Bathroom", "description": "You are in room: Master Bathroom" },
    {"title": "Study", "description": "You are in room: Study" },
    {"title": "Walk-in Closet", "description": "You are in room: Walk-in Closet" },
    {"title": "Secret Staircase", "description": "You are in room: Secret Staircase" },
    {"title": "Basement", "description": "You are in room: Basement" },
    {"title": "Family Room", "description": "You are in room: Family Room" },
    {"title": "Kitchen", "description": "You are in room: Kitchen" },
    {"title": "Computer Room", "description": "You are in room: Computer Room" },
    {"title": "Laundry Room", "description": "You are in room: Laundry Room" },
    {"title": "Game Room", "description": "You are in room: Game Room" },
    {"title": "Back Room", "description": "You are in room: Back Room" },
    {"title": "Bed Room", "description": "You are in room: Bed Room" },
    {"title": "Outside", "description": "You are in room: Outside" },
    {"title": "Cabin", "description": "You are in room: Cabin" },
    {"title": "Cellar", "description": "You are in room: Cellar" },
    {"title": "Pole Barn", "description": "You are in room: Pole Barn" },
    {"title": "Stable", "description": "You are in room: Stable" },
    {"title": "MudRoom", "description": "You are in room: MudRoom" },
    {"title": "Common Room", "description": "You are in room: Common Room" },
    {"title": "Breakfast Nook", "description": "You are in room: Breakfast Nook" },
    {"title": "Den", "description": "You are in room: Den" },
    {"title": "Sun Room", "description": "You are in room: Sun Room" },
    {"title": "Game Room", "description": "You are in room: Game Room" },
    {"title": "Garage", "description": "You are in room: MudRoom" },
    {"title": "Front Room", "description": "You are in room: Front Room" },
    {"title": "Guest Room", "description": "You are in room: Guest Room" },
    {"title": "Gym", "description": "You are in room: Gym" },
    {"title": "Hall", "description": "You are in room: Hall" },
    {"title": "Green Room", "description": "You are in room: Green Room" },
    {"title": "Keep", "description": "You are in room: Keep" },
    {"title": "Lobby", "description": "You are in room: Lobby" },
    {"title": "Lounge", "description": "You are in room: Lounge" },
    {"title": "Loft", "description": "You are in room: Great Room" },
    {"title": "ladies' Room", "description": "You are in room: ladies' Room" },
    {"title": "Wine Cellar", "description": "You are in room: Wine Cellar" },
    {"title": "Armory", "description": "You are in room: Armory" },
    {"title": "School Room", "description": "You are in room: School Room" },
    {"title": "Art Studio", "description": "You are in room: Art Studio" },
    {"title": "Meeting Room", "description": "You are in room: Meeting Room" },
    {"title": "Great Hall", "description": "You are in room: Great Hall" },
    {"title": "Broom Closet", "description": "You are in room: Broom Closet" },
    {"title": "Bar", "description": "You are in room: Bar" },
    {"title": "Nursery", "description": "You are in room: Nursery" },
    {"title": "Kitchenette", "description": "You are in room: Kitchenette" },
    {"title": "Hair Salon", "description": "You are in room: Hair Salon" },
    {"title": "Pool Hall", "description": "You are in room: Pool Hall" },
    {"title": "Gas Station", "description": "You are in room: Gas Station" },
    {"title": "Dog Room", "description": "You are in room: Dog Room" },
    {"title": "Cat Room", "description": "You are in room: Cat Room" },
    {"title": "Mini Zoo", "description": "You are in room: Mini Zoo" },
    {"title": "Balcony", "description": "You are in room: Balcony" },
    {"title": "Pool Room", "description": "You are in room: Garden" },
    {"title": "Mess Hall", "description": "You are in room: Mess Hall" },
    {"title": "Closet", "description": "You are in room: Closet" },
    {"title": "Narnia", "description": "You are in room: Narnia" },
    {"title": "Hogwarts", "description": "You are in room: Hogwarts" },
    {"title": "Cave", "description": "You are in room: Cave" },
    {"title": "Skyrim", "description": "You are in room: Skyrim" },
    {"title": "Passageway", "description": "You are in room: Passageway" },
    {"title": "Bandit Camp", "description": "You are in room: Bandit Camp" },
    {"title": "Dining Hall", "description": "You are in room: Dining Hall" },
    {"title": "Utility Closet", "description": "You are in room: Utility Closet" },
    {"title": "Crawl Space", "description": "You are in room: Crawl Space" },
    {"title": "Hidden Great Room", "description": "You are in room: Hidden Great Room" },
    {"title": "Dance hall", "description": "You are in room: Dance hall" },
    {"title": "Treasure Room", "description": "You are in room: Treasure Room" },
    {"title": "Library", "description": "You are in room: Library" },
    {"title": "Kitchen", "description": "You are in room: Kitchen" },
    {"title": "Town Hall", "description": "You are in room: Town Hall" },
    {"title": "Room of the Elders", "description": "You are in room: Room of the Elders" },
    {"title": "Empty Room", "description": "You are in room: Empty Room" },
    {"title": "Candle Lit Study", "description": "You are in room: Candle Lit Study" },
    {"title": "Hallway", "description": "You are in room: Hallway" },
    {"title": "Narrow Passage", "description": "You are in room: Narrow Passage" },
    {"title": "Balcony", "description": "You are in room: Balcony" },
    {"title": "Luxury Guest Room", "description": "You are in room: Luxury Guest Room" },
    {"title": "The Room of Movies", "description": "You are in room: The Room of Movies" },
    {"title": "The Room of Video Games", "description": "You are in room: The Room of Video Games" },
    {"title": "The Room of Make Believe", "description": "You are in room: The Room of Make Believe" },
    {"title": "The Room of the 90's", "description": "You are in room: The Room of the 90's" },
    {"title": "Shoe Room", "description": "You are in room: Shoe Room" },
    {"title": "Dining Room", "description": "You are in room: Dining Room" },
    {"title": "The Mage Room", "description": "You are in room: The Mage Room" },
    {"title": "The Warriors Room", "description": "You are in room: The Warriors Room" },
    {"title": "The Room of Imposter Syndrome", "description": "You are in room: The Room of Imposter Syndrome"},
    {"title": "The Room of Interviews", "description": "You are in room: The Room of Interviews" },
    {"title": "The Room of Possibilities", "description": "You are in room: The Room of Possibilities" },
    {"title": "The Room of Unanswered Applications", "description": "You are in room: The Room of Unanswered Applications" },
    {"title": "The Room of Maybes", "description": "You are in room: The Room of Maybes" },
    {"title": "The Room of Javascript Answers", "description": "You are in room:The Room of Javascript Answers" },
    {"title": "Python", "description": "You are in room: Python" },
    {"title": "The Room of Python", "description": "You are in room: The Room of Python" },
    {"title": "The Room of All Knowledge", "description": "You are in room: The Room of All Knowledge" },
    {"title": "Treasure Room", "description": "You are in room: Treasure Room" }
]

